version: "3.8"

services:

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fastapi_backend
    image: fastapi_backend
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure

volumes:
  data:
  pipcache:
  pgdata:
  postgres-data: null
