version: 2.1
orbs:
  python: circleci/python@2.1.1
  aws-ecr: circleci/aws-ecr@9.0.2

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.12
        environment:
          DATABASE_URL: "postgresql://ubuntu:ubuntu@localhost:5432/fastapi"
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: fastapi
          POSTGRES_PASSWORD: ubuntu
    
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Pipenv
          command: pip install pipenv
      - run:
          name: Install dependencies
          command: pipenv install
      - run:
          name: Run tests
          command: pipenv run python -m pytest 
          environment:
            DOMAIN: localhost
            SERVER_HOST: http://localhost
            PROJECT_NAME: sample
            SECRET_KEY: admin
            FIRST_SUPERUSER: admin@sample.com
            FIRST_SUPERUSER_NAME: Author
            FIRST_SUPERUSER_PASSWORD: admin
            USERS_OPEN_REGISTRATION: "True"
            DATABASE_URL: "postgresql://ubuntu:ubuntu@localhost:5432/fastapi"
            TEST_DATABASE_URL : "postgresql://ubuntu:ubuntu@localhost:5432/fastapi"
            TESTING: 1
      

workflows:
  fastapi_backend:
    jobs:
      - build_and_test
      - aws-ecr/build_and_push_image: # Use the pre-defined `build-and-push-image` job
          dockerfile: Dockerfile
          path: .
          repo: cd-okr
          tag: latest
