"""second migration

Revision ID: 7dc8bb46a47d
Revises: be9e05d37578
Create Date: 2023-07-04 13:23:53.195133

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7dc8bb46a47d"
down_revision = "be9e05d37578"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("item", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.alter_column("item", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("item", "description", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("item", "owner_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_index("ix_item_description", table_name="item")
    op.drop_index("ix_item_id", table_name="item")
    op.drop_index("ix_item_owner_id", table_name="item")
    op.drop_index("ix_item_title", table_name="item")
    op.add_column("user", sa.Column("date_of_joining", sa.DateTime(), nullable=True))
    op.add_column(
        "user", sa.Column("contact_number", sa.String(length=32), nullable=True)
    )
    op.add_column("user", sa.Column("address", sa.String(length=200), nullable=True))
    op.add_column("user", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("user", "full_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_index("ix_user_full_name", table_name="user")
    op.create_index(
        op.f("ix_user_hashed_password"), "user", ["hashed_password"], unique=True
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_hashed_password"), table_name="user")
    op.create_index("ix_user_full_name", "user", ["full_name"], unique=False)
    op.alter_column("user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "full_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("user", "is_deleted")
    op.drop_column("user", "address")
    op.drop_column("user", "contact_number")
    op.drop_column("user", "date_of_joining")
    op.create_index("ix_item_title", "item", ["title"], unique=False)
    op.create_index("ix_item_owner_id", "item", ["owner_id"], unique=False)
    op.create_index("ix_item_id", "item", ["id"], unique=False)
    op.create_index("ix_item_description", "item", ["description"], unique=False)
    op.alter_column("item", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("item", "description", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("item", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("item", "is_deleted")
    # ### end Alembic commands ###
